Name ="Rupam\nGoswami"
Age = 23
print(Name) 
# \n -- backslash

print("Name\tAge")
print("Rupam\t25")
# Tab

print("C:\\Users\\Rupam")
#Print Backslash

print("He said, \"hello\"")
# Double Quote inside String

print('It\'s Python')

print("12345\rRu")




import time

for i in range(5):
    print(f"\rProgress: {i}",end = "")
    time.sleep(1)
    


#Use of Input

# Answer = input("What's your name :-")
# print(Answer) 

print("\nstart", "Middle", "End",end = "")



